export const ActionTypes = {
  CHANGE_GENRE: `GENRE/CHANGE_GENER`,
  LOAD_FILMS: `DATA/LOAD_FILMS`,
  LOAD_PROMO: `DATA/LOAD_PROMO_FILM`,
  LOAD_FILM: `DATA/LOAD_FILM`,
  LOAD_COMMENT: `DATA/LOAD_COMMENT`,
  LOAD_FAVORITE_FILM: `DATA/LOAD_FAVORITE_FILM`,

  LOAD_USER: `USER/LOAD_USER`,
  REQUIRED_AUTHORIZATION: `USER/REQUIRED_AUTHORIZATION`,

  REDIRECT_TO_ROUTE: `ROUTE/REDIRECT_TO_ROUTE`,
  FORM_DISABLED: `ELEMENTS/FORM_DISABLED`,

  LOAD_FAILED: `ERROR/LOAD_FAILED`,
  RESET_FILM: `ERROR/RESET_FILM_LOAD`,
};
