export const ActionTypes = {
  CHANGE_GENRE: `GENRE/CHANGE_GENER`,
  LOAD_FILMS: `DATA/LOAD_FILMS`,
  LOAD_PROMO: `DATA/LOAD_PROMO_FILM`,
  LOAD_FILM: `DATA/LOAD_FILM`,
  LOAD_USER: `USER/LOAD_USER`,
  REQUIRED_AUTHORIZATION: `USER/REQUIRED_AUTHORIZATION`,
  RESET_FILM: `RESET/RESET_FILM_LOAD`,
  LOAD_FAILED: `ERROR/LOAD_FAILED`,
};
