export const ActionTypes = {
  CHANGE_GENRE: `DATA/CHANGE_GENER`,
  LOAD_FILMS: `DATA/LOAD_FILMS`,
  LOAD_PROMO: `DATA/LOAD_PROMO_FILM`,
  LOAD_FILM: `DATA/LOAD_FILM`,
  LOAD_COMMENT: `DATA/LOAD_COMMENT`,
  LOAD_FAVORITE_FILM: `DATA/LOAD_FAVORITE_FILM`,
  LOAD_FAVORITE_FILMS: `DATA/LOAD_FAVORITE_FILMS`,
  LOAD_FAILED: `DATA/LOAD_FAILED`,
  RESETLOAD_FILM: `DATA/RESET_FILM_LOAD`,

  LOAD_USER: `USER/LOAD_USER`,
  REQUIRED_AUTHORIZATION: `USER/REQUIRED_AUTHORIZATION`,

  FORM_DISABLED: `INTERFACE/FORM_DISABLED`,
  REDIRECT_TO_ROUTE: `ROUTING/REDIRECT_TO_ROUTE`,
};
